title: 'docs:NetStare'
description: Документация аналитической системы мониторинга NetStare
theme: just-the-docs

aux_links:
  "Подробнее о NetStare":
    - "https://netstare.ru"
aux_links_new_tab: true

url: https://netstare.ru

favicon_ico: "/images/favicon.png"
logo: "/images/logo.png"

callouts:
  warning:
    title: Внимание
    color: red
  important:
    title: Важно
    color: blue
  note:
    title: Заметка
    color: purple